language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
before-script: 
  - mysql -e 'create database forge;'
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan serve >/dev/null 2>&1 &

script: vendor/bin/phpunit