language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  
sudo: false

before_script: 
  - mysql -e 'create database sitarium;'
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan db:seed --class TestsSeeder
  - php artisan serve >/dev/null 2>&1 &

script: vendor/bin/phpunit